apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx-staging
namePrefix: staging-

commonLabels:
  env: staging

resources:
  - ../../base

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: nginx
    path: deployment-patch.json

configMapGenerator:
  - name: nginx-config
    files:
      - config/app.conf

secretGenerator:
  - name: nginx-secret
    literals:
      - DB_HOST=staging-db.internal
      - DB_PASSWORD=staging-secret-pass
      - API_KEY=staging-api-key-67890
