apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx-prod
namePrefix: prod-

commonLabels:
  env: prod

resources:
  - ../../base
  - hpa.yaml

patches:
  - path: deployment-patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: nginx
    path: resource-patch.json

configMapGenerator:
  - name: nginx-config
    files:
      - config/app.conf

secretGenerator:
  - name: nginx-secret
    literals:
      - DB_HOST=prod-db.internal
      - DB_PASSWORD=prod-secret-pass
      - API_KEY=prod-api-key-99999
