apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-prep
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: gitops-demo
    env: prep
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/melihekmekci1/gitops-demo.git
    targetRevision: main
    path: overlays/prep
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-prep
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
