apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-demo-root
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: gitops-demo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/melihekmekci1/gitops-demo.git
    targetRevision: main
    path: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
